from __future__ import annotations

from typing import Protocol

from mianotes_web_service.db.models import Note, Project, User


class UserRepository(Protocol):
    def add(self, user: User) -> User: ...
    def get(self, user_id: str) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...


class ProjectRepository(Protocol):
    def add(self, project: Project) -> Project: ...
    def get(self, project_id: str) -> Project | None: ...


class NoteRepository(Protocol):
    def add(self, note: Note) -> Note: ...
    def get(self, note_id: str) -> Note | None: ...
    def list_for_user(self, user_id: str) -> list[Note]: ...

